services:
  inkabot-backend:
    build: .
    restart: unless-stopped
    env_file: .env
    networks:
      - inkabot_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.inkabot-api.rule=Host(`api.inkabot.pe`)"
      - "traefik.http.routers.inkabot-api.entrypoints=websecure"
      - "traefik.http.routers.inkabot-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.inkabot-api.loadbalancer.server.port=8000"

networks:
  inkabot_network:
    external: true
